#lang racket/base
(struct ast-array-type () #:transparent)
(struct ast-integer-literal (value) #:transparent)
(struct ast-float-literal (value) #:transparent)
(struct ast-char-literal (value) #:transparent)
(struct ast-string-literal (value) #:transparent)
(struct ast-bool-literal (value) #:transparent)
(struct ast-null-literal (value) #:transparent)
(struct ast-text-block (value) #:transparent)
(provide (all-defined-out))